baseURL = "http://example.org/"
languageCode = "zh-CN"
title = "NG/C7å¯¼èˆªç«™ğŸ”¥ğŸ”¥ğŸ”¥"
theme = "hugo-webstack"

# æ˜¯å¦å…è®¸å¤§å†™å­—æ¯URLè·¯å¾„ï¼Œtrueï¼šå…è®¸ï¼›falseï¼šè½¬æ¢ä¸ºå°å†™
disablePathToLower = true

# é¡µè„šç‰ˆæƒä¿¡æ¯
copyright = "Â© 2025 NG/C7å¯¼èˆªç«™ - æƒå¨å¯¼èˆª"

# ç½‘ç«™SEOä¿¡æ¯ï¼ˆä»…ä¾›æœç´¢å¼•æ“å‚è€ƒï¼‰
[params]
  keywords = "NGå¨±ä¹,C7å¨±ä¹,æ¸¸æˆå¯¼èˆª,å®˜ç½‘å…¥å£,H5å¹³å°,çº¿ä¸Šå¨±ä¹å¹³å°,ä¼˜æƒ æ´»åŠ¨"
  description = "NG/C7å¯¼èˆªç«™ä¸ºæ‚¨æä¾›æœ€æ–°å®˜ç½‘å…¥å£ã€å®‰å…¨ä¾¿æ·çš„H5å¹³å°ä»¥åŠä¸°å¯Œçš„ä¼˜æƒ æ´»åŠ¨ï¼Œæ˜¯æ‚¨ç•…ç©æ¸¸æˆçš„æœ€ä½³é€‰æ‹©ã€‚"

# æ˜¯å¦å¼€å¯æœç´¢æ 
[params.search]
  enable = true

# é»˜è®¤æ¨¡å¼è®¾ç½®ï¼ˆtrueï¼šæš—è‰²æ¨¡å¼ï¼›falseï¼šäº®è‰²æ¨¡å¼ï¼‰
[params.darkmode]
  enable = false

# åœ¨çº¿ç¼–è¾‘æŒ‰é’®è®¾ç½®
[params.edit]
  enable = false

# GitHubä»£ç æŒ‰é’®è®¾ç½®ï¼ˆæ˜¾ç¤ºæˆ–éšè—ï¼‰
[params.github]
  enable = true
  url = "https://github.com/oulh/nav"
  
# è‡ªå®šä¹‰é¡µé¢è·¯å¾„
[permalinks]
  404 = "/404.html"

# æœ¬åœ°æœç´¢åŠŸèƒ½çš„æ‹¼éŸ³åŒ¹é…ï¼ˆtrueï¼šå¼€å¯ï¼›falseï¼šå…³é—­ï¼‰
[params.pinyin]
  enable = true
